//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliInvoke.Internal.Localizations {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CliInvoke.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Exceptions_CommandNotSuccessful_Generic {
            get {
                return ResourceManager.GetString("Exceptions.CommandNotSuccessful.Generic", resourceCulture);
            }
        }
        
        internal static string Exceptions_CommandNotSuccessful_Specific {
            get {
                return ResourceManager.GetString("Exceptions.CommandNotSuccessful.Specific", resourceCulture);
            }
        }
        
        internal static string Exceptions_FileNotFound {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound", resourceCulture);
            }
        }
        
        internal static string Process_FileName_Empty {
            get {
                return ResourceManager.GetString("Process.FileName.Empty", resourceCulture);
            }
        }
        
        internal static string CommandBuilder_ArgumentConflict_ShellExecution_Input {
            get {
                return ResourceManager.GetString("CommandBuilder.ArgumentConflict.ShellExecution.Input", resourceCulture);
            }
        }
        
        internal static string CommandBuilder_ArgumentConflict_ShellExecution_Output {
            get {
                return ResourceManager.GetString("CommandBuilder.ArgumentConflict.ShellExecution.Output", resourceCulture);
            }
        }
        
        internal static string CommandBuilder_ArgumentConflict_ShellExecution_Error {
            get {
                return ResourceManager.GetString("CommandBuilder.ArgumentConflict.ShellExecution.Error", resourceCulture);
            }
        }
        
        internal static string Exceptions_ArgumentBuilder_Buffer_MaximumSize {
            get {
                return ResourceManager.GetString("Exceptions.ArgumentBuilder.Buffer.MaximumSize", resourceCulture);
            }
        }
        
        internal static string Exceptions_TargetFile_NullOrEmpty {
            get {
                return ResourceManager.GetString("Exceptions.TargetFile.NullOrEmpty", resourceCulture);
            }
        }
        
        internal static string Exceptions_ProcessNotSuccessful_Generic {
            get {
                return ResourceManager.GetString("Exceptions.ProcessNotSuccessful.Generic", resourceCulture);
            }
        }
        
        internal static string Exceptions_ProcessNotSuccessful_Specific {
            get {
                return ResourceManager.GetString("Exceptions.ProcessNotSuccessful.Specific", resourceCulture);
            }
        }
        
        internal static string Exceptions_ResourcePolicy_CannotSetToNonStartedProcess {
            get {
                return ResourceManager.GetString("Exceptions.ResourcePolicy.CannotSetToNonStartedProcess", resourceCulture);
            }
        }
        
        internal static string Exceptions_Processes_NotSupportedOnRemoteProcess {
            get {
                return ResourceManager.GetString("Exceptions.Processes.NotSupportedOnRemoteProcess", resourceCulture);
            }
        }
    }
}
