### YamlMime:ManagedReference
items:
- uid: AlastairLundy.CliInvoke.Specializations.Configurations
  commentId: N:AlastairLundy.CliInvoke.Specializations.Configurations
  id: AlastairLundy.CliInvoke.Specializations.Configurations
  children:
  - AlastairLundy.CliInvoke.Specializations.Configurations.ClassicPowershellCommandConfiguration
  - AlastairLundy.CliInvoke.Specializations.Configurations.CmdCommandConfiguration
  - AlastairLundy.CliInvoke.Specializations.Configurations.PowershellCommandConfiguration
  langs:
  - csharp
  - vb
  name: AlastairLundy.CliInvoke.Specializations.Configurations
  nameWithType: AlastairLundy.CliInvoke.Specializations.Configurations
  fullName: AlastairLundy.CliInvoke.Specializations.Configurations
  type: Namespace
  assemblies:
  - AlastairLundy.CliInvoke.Specializations
references:
- uid: AlastairLundy.CliInvoke.Specializations.Configurations.ClassicPowershellCommandConfiguration
  commentId: T:AlastairLundy.CliInvoke.Specializations.Configurations.ClassicPowershellCommandConfiguration
  href: AlastairLundy.CliInvoke.Specializations.Configurations.ClassicPowershellCommandConfiguration.html
  name: ClassicPowershellCommandConfiguration
  nameWithType: ClassicPowershellCommandConfiguration
  fullName: AlastairLundy.CliInvoke.Specializations.Configurations.ClassicPowershellCommandConfiguration
- uid: AlastairLundy.CliInvoke.Specializations.Configurations.CmdCommandConfiguration
  commentId: T:AlastairLundy.CliInvoke.Specializations.Configurations.CmdCommandConfiguration
  href: AlastairLundy.CliInvoke.Specializations.Configurations.CmdCommandConfiguration.html
  name: CmdCommandConfiguration
  nameWithType: CmdCommandConfiguration
  fullName: AlastairLundy.CliInvoke.Specializations.Configurations.CmdCommandConfiguration
- uid: AlastairLundy.CliInvoke.Specializations.Configurations.PowershellCommandConfiguration
  commentId: T:AlastairLundy.CliInvoke.Specializations.Configurations.PowershellCommandConfiguration
  href: AlastairLundy.CliInvoke.Specializations.Configurations.PowershellCommandConfiguration.html
  name: PowershellCommandConfiguration
  nameWithType: PowershellCommandConfiguration
  fullName: AlastairLundy.CliInvoke.Specializations.Configurations.PowershellCommandConfiguration
