name: site

on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - id: lunet
        name: Build and deploy Lunet site
        uses: lunet-io/actions/lunet-build@324085f316e425108daa2183106c6ace59d6ee2d # v1
        with:
          site_path: site
