- name: Release Drafter
  uses: release-drafter/release-drafter@v6.0.0
  
  with:
    # If your workflow requires multiple release-drafter configs it be helpful to override the config-name.
    The config should still be located inside `.github` as that's where we are looking for config files.

    config-name: # optional, default is release-drafter.yml
    # The name that will be used in the GitHub release that's created or updated.
This will override any `name-template` specified in your `release-drafter.yml` if defined.

    name: # optional
    # The tag name to be associated with the GitHub release that's created or updated.
This will override any `tag-template` specified in your `release-drafter.yml` if defined.

    tag: # optional
    # The version to be associated with the GitHub release that's created or updated.
This will override any version calculated by the release-drafter.

    version: # optional
    # A boolean indicating whether the release being created or updated should be immediately published.

    publish: false
    # A string indicating whether the release being created or updated should be marked as latest.

    latest: # optional, default is 
    # A boolean indicating whether the release being created or updated is a prerelease.

    prerelease: # optional, default is 
    # A string indicating an identifier (alpha, beta, rc, etc), to increment the prerelease version.

    prerelease-identifier: # optional, default is 
    # The object that the release should be created to point to.

    commitish: # optional, default is 
    # A string that would be added before the template body.

    header: # optional, default is 
    # A string that would be added after the template body.

    footer: # optional, default is 
    # A boolean indicating whether the releaser mode is disabled.

    disable-releaser: false
    # A boolean indicating whether the autolabeler mode is disabled.

    disable-autolabeler: # optional, default is 
          
